# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/':  # Esto aplica la regla a todas las rutas
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link']
            max_age: 3600
            allow_credentials: true
